// Pure task-mutation rules from lib/use-tasks.ts: the done-flip
// completedAt stamping and the reschedule move-count bump. The web hook
// wraps these with localStorage + Supabase writes; the rules themselves
// are pure and injected with `nowISO` for determinism.

import Foundation

/// First done-flip captures the completion time; subsequent toggles
/// preserve the original. Un-completing CLEARS the timestamp so a later
/// re-completion re-stamps fresh (otherwise a stale date suppresses the
/// "completed today" win and mis-dates analytics).
public func stampCompletion(isDone: Bool, incomingCompletedAt: String?, priorCompletedAt: String?, nowISO: String) -> String? {
    isDone ? (incomingCompletedAt ?? priorCompletedAt ?? nowISO) : nil
}

/// Apply the completion stamp + bump updatedAt to `item`, given its prior
/// stored version (for the preserve-original-timestamp rule).
public func applyCompletion(_ item: TaskItem, prior: TaskItem?, nowISO: String) -> TaskItem {
    var next = item
    next.completedAt = stampCompletion(
        isDone: item.done,
        incomingCompletedAt: item.completedAt,
        priorCompletedAt: prior?.completedAt,
        nowISO: nowISO)
    next.updatedAt = nowISO
    return next
}

/// Increment a task's reschedule counter (feeds the slip detector).
public func bumpMoveCount(_ task: TaskItem, nowISO: String) -> TaskItem {
    var next = task
    next.moveCount = (task.moveCount ?? 0) + 1
    next.updatedAt = nowISO
    return next
}

/// Scheduling a task ENDS its "Later" parking: "park this for Later" and "it's
/// on Tuesday at 2" are mutually exclusive states. Returns the task with
/// `later` cleared when `block` schedules a task that is still parked, else nil
/// (nothing to write).
///
/// Without this the task appeared on the calendar at the time the user picked
/// while every active list filtered it out as deferred — /tasks Today, Backlog
/// and Upcoming, the Today tab's list and Start-Next all exclude `later` — and
/// only the Later tab still showed it. Only the Task-editor's own Schedule
/// sheet cleared the flag; a calendar drop, the assistant's `schedule_task`
/// and the loop-promote path did not.
///
/// Recurring TEMPLATES are skipped: their occurrence blocks are generated by
/// the horizon regen, not a manual scheduling decision (and projected
/// occurrence rows are `later: false` already).
public func unparkedTaskForBlock(_ block: CalBlock, tasks: [TaskItem], nowISO: String) -> TaskItem? {
    guard isTaskBlock(block), let taskId = block.taskId,
          let task = tasks.first(where: { $0.id == taskId }),
          task.later == true, task.recurrence == nil else { return nil }
    var next = task
    next.later = false
    next.updatedAt = nowISO
    return next
}

// MARK: label cascades (area / tag rename + delete)
//
// Tasks carry their life area and tags as plain NAME strings, not row ids, so
// renaming or deleting the vocabulary row has to follow onto every task that
// names it. Settings used to write only the row: after "Personal" → "Life" the
// Life pill showed nothing, its count read 0, and web/Android still said
// Personal (audit 2026-09-22, C19). Each returns the rewritten task, or nil
// when the task doesn't carry the label (nothing to write).

/// Area rename (`new` = the new name) or delete (`new` = nil). EXACT match,
/// like the web's cascadeRenameTaskArea, Android's renameLifeArea /
/// deleteLifeArea and the Today pill filter.
public func relabelingArea(_ task: TaskItem, from old: String, to new: String?, nowISO: String) -> TaskItem? {
    guard task.lifeArea == old else { return nil }
    var next = task
    next.lifeArea = new
    next.updatedAt = nowISO
    return next
}

/// Tag rename. Case-insensitive, like the tag filter and Android's renameTag;
/// a task that already carries the new name keeps a single copy.
public func renamingTag(_ task: TaskItem, from old: String, to new: String, nowISO: String) -> TaskItem? {
    let tags = task.tags ?? []
    guard tags.contains(where: { $0.caseInsensitiveCompare(old) == .orderedSame }) else { return nil }
    var seen = Set<String>()
    var next = task
    next.tags = tags.map { $0.caseInsensitiveCompare(old) == .orderedSame ? new : $0 }
        .filter { seen.insert($0.lowercased()).inserted }
    next.updatedAt = nowISO
    return next
}

/// Tag delete: strip every case-insensitive match; an emptied list is nil.
public func strippingTag(_ task: TaskItem, name: String, nowISO: String) -> TaskItem? {
    let tags = task.tags ?? []
    guard tags.contains(where: { $0.caseInsensitiveCompare(name) == .orderedSame }) else { return nil }
    let stripped = tags.filter { $0.caseInsensitiveCompare(name) != .orderedSame }
    var next = task
    next.tags = stripped.isEmpty ? nil : stripped
    next.updatedAt = nowISO
    return next
}

/// Does another row already use `name`, ignoring case? The same rule as the
/// Settings Add check; the server's unique(user_id, name) would reject the
/// exact-case twin and quarantine the row.
public func labelNameTaken(_ name: String, among others: [String]) -> Bool {
    others.contains { $0.caseInsensitiveCompare(name) == .orderedSame }
}

/// Where an area filter (Today / Tasks pills, held by NAME) points after the
/// area rows change: unchanged while an area still has that name, the row's
/// new name when it was renamed, nil (All) when it was deleted. Now that the
/// cascade moves every task off the old name, a filter left on it matched
/// nothing — no pill lit and "Nothing in Personal right now." (audit
/// 2026-09-22, C19).
public func areaFilterFollowing(_ filter: String?, from old: [LifeArea], to new: [LifeArea]) -> String? {
    guard let filter, !new.contains(where: { $0.name == filter }) else { return filter }
    let ids = Set(old.filter { $0.name == filter }.map(\.id))
    return new.first { ids.contains($0.id) }?.name
}

/// May a focus finish that resolved NO occurrence block flip THIS row's own
/// `done`? Never for a recurring TEMPLATE.
///
/// A template's `done` ends the whole series — it stops generating occurrences
/// and shows in no list — which is never what "I finished this session" means.
/// The session normally carries the day's block (set at start), but the
/// starts-now notification's "Start" hands focus the template, and when today's
/// occurrence was ticked or skipped between the notification and the tap no
/// block resolves at all. Finishing with "Done" then silently ended the series.
/// The session's time still accrues on the template either way; only the
/// completion flip is withheld.
public func focusMayCompleteRow(_ task: TaskItem) -> Bool { task.recurrence == nil }
