// Pure task-mutation rules from lib/use-tasks.ts: the done-flip
// completedAt stamping and the reschedule move-count bump. The web hook
// wraps these with localStorage + Supabase writes; the rules themselves
// are pure and injected with `nowISO` for determinism.

import Foundation

/// First done-flip captures the completion time; subsequent toggles
/// preserve the original. Un-completing CLEARS the timestamp so a later
/// re-completion re-stamps fresh (otherwise a stale date suppresses the
/// "completed today" win and mis-dates analytics).
public func stampCompletion(isDone: Bool, incomingCompletedAt: String?, priorCompletedAt: String?, nowISO: String) -> String? {
    isDone ? (incomingCompletedAt ?? priorCompletedAt ?? nowISO) : nil
}

/// Apply the completion stamp + bump updatedAt to `item`, given its prior
/// stored version (for the preserve-original-timestamp rule).
public func applyCompletion(_ item: TaskItem, prior: TaskItem?, nowISO: String) -> TaskItem {
    var next = item
    next.completedAt = stampCompletion(
        isDone: item.done,
        incomingCompletedAt: item.completedAt,
        priorCompletedAt: prior?.completedAt,
        nowISO: nowISO)
    next.updatedAt = nowISO
    return next
}

/// Increment a task's reschedule counter (feeds the slip detector).
public func bumpMoveCount(_ task: TaskItem, nowISO: String) -> TaskItem {
    var next = task
    next.moveCount = (task.moveCount ?? 0) + 1
    next.updatedAt = nowISO
    return next
}

/// Scheduling a task ENDS its "Later" parking: "park this for Later" and "it's
/// on Tuesday at 2" are mutually exclusive states. Returns the task with
/// `later` cleared when `block` schedules a task that is still parked, else nil
/// (nothing to write).
///
/// Without this the task appeared on the calendar at the time the user picked
/// while every active list filtered it out as deferred — /tasks Today, Backlog
/// and Upcoming, the Today tab's list and Start-Next all exclude `later` — and
/// only the Later tab still showed it. Only the Task-editor's own Schedule
/// sheet cleared the flag; a calendar drop, the assistant's `schedule_task`
/// and the loop-promote path did not.
///
/// Recurring TEMPLATES are skipped: their occurrence blocks are generated by
/// the horizon regen, not a manual scheduling decision (and projected
/// occurrence rows are `later: false` already).
public func unparkedTaskForBlock(_ block: CalBlock, tasks: [TaskItem], nowISO: String) -> TaskItem? {
    guard isTaskBlock(block), let taskId = block.taskId,
          let task = tasks.first(where: { $0.id == taskId }),
          task.later == true, task.recurrence == nil else { return nil }
    var next = task
    next.later = false
    next.updatedAt = nowISO
    return next
}

/// May a focus finish that resolved NO occurrence block flip THIS row's own
/// `done`? Never for a recurring TEMPLATE.
///
/// A template's `done` ends the whole series — it stops generating occurrences
/// and shows in no list — which is never what "I finished this session" means.
/// The session normally carries the day's block (set at start), but the
/// starts-now notification's "Start" hands focus the template, and when today's
/// occurrence was ticked or skipped between the notification and the tap no
/// block resolves at all. Finishing with "Done" then silently ended the series.
/// The session's time still accrues on the template either way; only the
/// completion flip is withheld.
public func focusMayCompleteRow(_ task: TaskItem) -> Bool { task.recurrence == nil }

/// The server CHECK is `estimate_min between 1 and 1440` (migration 001). An
/// out-of-range value is accepted locally, rejected by PostgREST on flush,
/// retried five times and then quarantined — the row lives on that one phone
/// for ever and the user is never told (audit 2026-09-21). Clamp instead.
/// The ONE rule for the estimate range: WriteThrough and the wire codec clamp
/// with it too, so a writer that forgets can no longer strand a row (audit
/// 2026-09-22, C4).
public func clampEstimateMin(_ raw: Int?) -> Int { min(1440, max(1, raw ?? 25)) }

/// `duration_minutes between 5 and 1440` (migration 001), so a 2-minute task
/// would otherwise mint a block the server refuses. The ONE rule for a block's
/// length: recurrence minting, WriteThrough and the wire codec all use it
/// (audit 2026-09-22, C4).
public func clampDurationMin(_ raw: Int?, fallback: Int = 25) -> Int { min(1440, max(5, raw ?? fallback)) }
